version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=myapp
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=myapp
      - DB_USER=root
      - DB_PASS=rootroot
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootroot
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: